explorerv10
descope-sample-apps/descope-explorer pull request #36
Opened 2023-08-05 00:13 UTC by eric-prog

Explorer improvements:
- remove theme field in Descope Explorer
- change "Join the Slack" to "Join our community"
- remove "star us on github" button.

Issue: https://github.com/orgs/descope/projects/14/views/5?pane=issue&itemId=34671627

2023-08-10 13:08 UTC, gshriki requested changes
1. center of these elements looks weird:
![image](https://github.com/descope-sample-apps/descope-explorer/assets/1042046/16a47d9e-99e7-4b97-9f6f-1c996d0a3001)

not sure what you can do about it thought

2. Bug. Go into the settings page, change delete the last character and type it again. Click update. 
![image](https://github.com/descope-sample-apps/descope-explorer/assets/1042046/1ece2ed3-d579-434d-93dd-d8bdb704524c)

The flow is now specified in the project parameter in the url

4. Join our community - check with @rishibhargava if he wants to use the direct Slack URL, or take the user to the join the community page in our website (for analytics)

5. can we align the background color of the flow frame and the flow itself in dark mode?

![image](https://github.com/descope-sample-apps/descope-explorer/assets/1042046/306018df-b09c-40eb-ab54-be834c08a465)

2023-08-10 13:50 UTC, rishibhargava commented
The community should be to the web page and not the slack url.


On Thu, Aug 10 2023 at 6:09 AM, Gilad Shriki ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
>    1. center of these elements looks weird:
>    [image: image]
>    <https://user-images.githubusercontent.com/1042046/259748857-16a47d9e-99e7-4b97-9f6f-1c996d0a3001.png>
>
> not sure what you can do about it thought
>
>    1. Bug. Go into the settings page, change delete the last character
>    and type it again. Click update.
>    [image: image]
>    <https://user-images.githubusercontent.com/1042046/259749275-1ece2ed3-d579-434d-93dd-d8bdb704524c.png>
>
> The flow is now specified in the project parameter in the url
>
>    1.
>
>    Join our community - check with @rishibhargava
>    <https://github.com/rishibhargava> if he wants to use the direct Slack
>    URL, or take the user to the join the community page in our website (for
>    analytics)
>    2.
>
>    can we align the background color of the flow frame and the flow
>    itself in dark mode?
>
> [image: image]
> <https://user-images.githubusercontent.com/1042046/259750860-306018df-b09c-40eb-ab54-be834c08a465.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/descope-sample-apps/descope-explorer/pull/36#pullrequestreview-1571857610>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKMP5TUYJU2QWKOSNK7JF3XUTMOZANCNFSM6AAAAAA3E2IXSY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2023-08-10 17:51 UTC, dorsha commented
Let's also add locale, but in the next PR once will be in production.

2023-08-11 17:35 UTC, gshriki approved these changes

2023-08-11 20:10 UTC, merged